### ISSUE TITLE
Not running properly for me

### ISSUE THREAD

**Issue by saurabhjain1592** [BrunoDeBarros/git-deploy-php#63] opened 2015-09-16 11:56 UTC
Warning: array_merge(): Argument #2 is not an array in phar:///Users/saurabhjain/Documents/workspace_ridorama/ridorama-backend/git-deploy/src/Config.php on line 75
Enter ftp password: 

Fatal error: Class 'Brunodebarros\Gitdeploy\' not found in phar:///Users/saurabhjain/Documents/workspace_ridorama/ridorama-backend/git-deploy/src/Config.php on line 92

**Comment by cfabrice** [comment] 2015-11-05 12:30
Same error here ! too bad...

**Comment by cfabrice** [comment] 2015-11-05 12:34
here is my error:
```
iMacWonder-3:testdebarros f$ php git-deploy
PHP Warning:  array_merge(): Argument #2 is not an array in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 76

Warning: array_merge(): Argument #2 is not an array in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 76
Enter ftp password: 
PHP Notice:  Undefined index: skip in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 88

Notice: Undefined index: skip in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 88
PHP Notice:  Undefined index: scheme in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 92

Notice: Undefined index: scheme in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 92
PHP Fatal error:  Class 'Brunodebarros\Gitdeploy\' not found in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 93

Fatal error: Class 'Brunodebarros\Gitdeploy\' not found in phar:///Users/f/Desktop/testdebarros/git-deploy/src/Config.php on line 93
```

**Comment by BrunoDeBarros** [comment] 2015-11-05 18:07
That's a strange error; thanks for letting me know. I'll be looking into it over the weekend if I get a chance, and I'll see if I can resolve it.

What version of PHP are you running?

**Comment by cfabrice** [comment] 2015-11-05 19:04
Hello, 
Thank you for your answer !
it’s PHP 5.4
Fabrice

**Comment by BrunoDeBarros** [comment] 2015-11-09 11:55
I see what the problem is. Your deploy file is like this:

`[ftp://example:password@example.com:21/path/to/installation]`

Right? If that's the case, try using the normal way of specifying servers:

```
[example]

skip = false
user = example
pass = password    
host = example.com
port = 21
path = /path/to/installation
passive = true
```

**Comment by cfabrice** [comment] 2015-11-09 12:13
no, i’m using the normal way…

**Comment by BrunoDeBarros** [comment] 2015-11-09 12:15
What is your deploy.ini like? It looks like it's a problem with the deploy configs.

**Comment by cfabrice** [comment] 2015-11-09 14:48
There you are…

skip = false
user = ksud_wonderweb
pass = XXXXXX
host = http://ksudbtrv.preview.infomaniak.com
port = 21
path = /test
passive = true

**Comment by BrunoDeBarros** [comment] 2015-11-09 14:59
Do you not have a section header at the top? Like:

```
[ksudbtrv]
```

Notice that in my example I have `[example]` before the rest of the details.

**Comment by cfabrice** [comment] 2015-11-09 16:25
you were right, I didn’t know it was useful… I’m not familiarized with .ini file. 
but nonetheless even with the header (i can name it as i want, correct ? or do i have to use the domain without the extension or the user as in your example?) I still get an error: 

ERROR: Could not connect to ftp://user@http://domain.ch:21/web/path/otherpath

About my setting: my local repository is in a folder in my desktop folder (I’m on mac). 
I just have an index.html file at its root and your files (deploy.ini, git-deploy and the folder called tools), is this correct ?
I cd in my folder with terminal and I typed php git-deploy. Correct ?
Do I have to install something on the distant server as well ?

**Comment by BrunoDeBarros** [comment] 2015-11-09 16:27
You can use whatever you want.

It sounds like your host is wrong - it's not supposed to include `http://`.

Everything should work well, but it does look like the config file has some problems.

**Comment by cfabrice** [comment] 2015-11-09 18:07
Ok, it ’s probably the server… because I’ve tried on another one (hosted at Sitegroud) and it worked perfectly. Thanks a lot !
The first time I deployed it uploaded all your files (I think it is because I git clone your repository and didn’t trash the .git folder and change the origin, correct !?)
Should I have gitignored them first ? will they be ignore then ? 
Or should I have used deploy.ini as in your doc with adding as many lines like this ignore_files[] = file/toignore.txt ?
Is there a way to ignore a whole folder and its content ?
Thanks a lot anyway - I hope I can see why it is not working with the server as this is our main hosting provider.

**Comment by BrunoDeBarros** [comment] 2015-11-09 18:08
Shot in the dark: Does your password have special characters? If it does, it should be wrapped with quotes. So:

```
skip = false
user = BBBB
pass = "XXXXXX"
host = HHHH
```

That might actually be the problem.

**Comment by BrunoDeBarros** [comment] 2015-11-09 18:12
.git and any git-related files are ignored automatically, and it doesn't change anything in your original directory. git-deploy only includes files tracked in the repository, so any files that weren't committed into the repository won't be deployed (unless you use `upload_untracked[]`).

To ignore a whole folder, you can just do `ignore_directories[] = path/to/folder`. That should do it.

**Comment by cfabrice** [comment] 2015-11-09 18:12
ok for the password: capital and small letters should dot it, right. 
but the user has an underscore (hosting obligation), could it be this ?

**Comment by BrunoDeBarros** [comment] 2015-11-09 18:12
Try it!

**Comment by BrunoDeBarros** [comment] 2015-11-09 18:13
Try it with quotes. Also, add quotes to things like the host, the user, anything you think that might cause problems.

**Comment by cfabrice** [comment] 2015-11-09 18:13
ok thanks a lot !

**Comment by cfabrice** [comment] 2015-11-09 22:58
So cool ! it worked with quotes ;-)

**Comment by BrunoDeBarros** [comment] 2015-11-10 10:39
Sweet, I'm glad to hear that! So really, the problem was just the configurations being incorrect. I'm closing this ticket.

**Closed by BrunoDeBarros** 2015-11-10 10:39 UTC
