### ISSUE TITLE
Unable to access the git repository's folder.

### ISSUE THREAD

**Issue by nolfranklin** [BrunoDeBarros/git-deploy-php#52] opened 2015-02-05 23:07 UTC
Love the idea of this script but having a few issues getting it setup. 

I'm using the following for my deploy.ini:

```
; This is a sample deploy.ini file.

[example]

scheme = sftp
skip = false
user = root
pass = password
host = 162.243.152.193
port = 22
path = /root/nols
passive = true
```

I dropped the git-deploy.phar file in the root of my project. I've tried with and without the /tools folder as well but I keep getting 

```
Unable to access the git repository's folder.

and

Warning: chdir(): No such file or directory (errno 2) in phar:///...git-deploy/src/Git.php on line 95

```

I have an inited .git folder with a few commits as well and my hosting is on digital ocean. I can SSH and SFTP into the account without trouble. 

Thanks for your help!

**Comment by BrunoDeBarros** [comment] 2015-02-05 23:39
Sorry about this; we've just switched to a .phar literally a few days ago to help with development, and there's probably something going on with it that I'm not finding in my environment. I'll try it out in a clean VM in a minute.

**Comment by nolfranklin** [comment] 2015-02-05 23:46
Ah, greatly appreciated. Thanks @BrunoDeBarros!

**Comment by BrunoDeBarros** [comment] 2015-02-07 15:13
I've just fixed this. :smile: It was indeed caused by the switch to .phar I'm afraid. I didn't notice it because I use the --repo-path option to keep one global copy of git-deploy in my PATH, and just use it to deploy any of my projects like that. Can you try it now?

**Comment by nolfranklin** [comment] 2015-02-07 15:35
@BrunoDeBarros, you just made my weekend! It works perfectly! Thank you times a million!

**Comment by BrunoDeBarros** [comment] 2015-02-07 15:36
My pleasure! I'm closing this issue now, but please let me know if you need anything else at all! :smile:

**Closed by BrunoDeBarros** 2015-02-07 15:36 UTC
